name: "dingo"
N: 30
integrator_step: 0.1
n_discs: 1

solver_settings:
  solver: "casadi"

params:
  save_map: true

recording:
  enable: false
  folder: "tests"
  file: "planner_test_output"
  timestamp: true
  num_experiments: 5

debug_limits: true
debug_output: false

enable_output: true
control_frequency: 20
deceleration_at_infeasible: 3.0
max_obstacles: 3
n_discs: 0.325
robot:
  length: 0.65
  width: 0.65
  com_to_back: 0.0
obstacle_radius: 0.35

linearized_constraints:
  add_halfspaces: 0 #2  # For road constraints

scenario_constraints:
  parallel_solvers: 1

road:
  two_way: false
  width: 7.0

shift_previous_solution_forward: false

contouring:
  dynamic_velocity_reference: false
  num_segments: 3
  preview: 0.0
  add_road_constraints: true

t-mpc:
  use_t-mpc++: true
  enable_constraints: true
  highlight_selected: true
  warmstart_with_mpc_solution: false

probabilistic:
  enable: true
  risk: 0.05
  propagate_uncertainty: true

weights:
  goal: 0.5
  velocity: 0.3 
  acceleration_x: 0.25 #0.15
  acceleration_y: 0.25 #0.15
  angular_velocity: 0.5 #0.25 
  reference_velocity: 1.5 #2.0 
  contour: 0.05 #0.01 #0.05
  preview: 0.0
  lag: 0.1
  slack: 10000.

visualization:
  draw_every: 5 # stages