GAUSSIAN = "GAUSSIAN"
PROBABILISTIC = "PROBABILISTIC"
DETERMINISTIC = "DETERMINISTIC"
PATH_FOLLOWING = "PATH_FOLLOWING"
LINEAR = "LINEAR"
OBJECTIVE = "OBJECTIVE"
CONSTRAINT = "CONSTRAINT"
DYNAMIC = "DYNAMIC"

WEIGHT_PARAMS = [

]

BISECTION_TOLERANCE = 1e-6